name: CI/CD Pipeline Deploy to AWS/EC2 - website

run-name: ${{ github.actor }} | Deploy to AWS/EC2 🚀
on:
  push:
    branches: [ feat/website ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # Step 1
    - name: Get Github action IP
      id: ip
      uses: haythem/public-ip@v1.2
    
    # Step 2
    - name: Add Github Actions IP to Security group
      run:
        aws ec2 authorize-security-group-ingress --group-name ${{ secrets.AWS_SG_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32    
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    # Step 3
    - name: Set up Node.js using nvm
      run: |
        export NVM_DIR=$HOME/.nvm
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install 20.5.0
        nvm use 20.5.0
      shell: bash

    # Step 4
    - name: Deploy to prod server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/ubuntu/project/goodjob
          git stash
          git pull origin feat/website
          npm install -g npm@7
          npm install
          pm2 restart PM2-Node

    # Step 5    
    - name: Remove Github Actions IP from security group
      run: |
        aws ec2 revoke-security-group-ingress --group-name ${{ secrets.AWS_SG_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      if: always()