name: CI Unit Test - JavaScript

run-name: ${{ github.actor }} | Testing for JavaScript 🔍
on:
  push:
    branches:
      - feat/website
      - feat/refactor
      - test
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
    
    - name: Result notification
      run: echo "✅ Test ${{ job.status }}."
      if: success()
    
    - name: Trigger CD pipeline
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          https://github.com/rubywu0604/GoodJob.git \
          -d '{"event_type": "trigger-cd-pipeline"}'